services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postchain
      POSTGRES_PASSWORD: postchain
      POSTGRES_INITDB_ARGS: "--lc-collate=C.UTF-8 --lc-ctype=C.UTF-8 --encoding=UTF-8"
      # POSTGRES_INITDB_ARGS: "--lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8 --encoding=UTF-8" # Docker for Mac